module.exports = {
    content: ['./**/*.html', './**/*.js'],
    css: ['./assets/bootstrap/bootstrap.min.css'], // Spécifiez le chemin de vos fichiers CSS
    whitelist: [
      // Ajoutez la liste blanche des classes ici
      'gallery-item',
      'row',
      'gallery-items-row',
      'item-column',
      'mb-4',
      'col-md-4',
      'col-lg-4',
      'col-xl-4',
      'col',
      'col-sm-6',
      'col-12',
      'col-sm',
      'col-md',
      'col-lg',
      'col-xl',
      'img-fluid',
      'modal',
      'modal-dialog',
      'modal-content',
      'modal-body',
      'mg-prev',
      'mg-next',
      'lightboxImage',
      'my-4',
      'tags-bar',
      'nav',
      'nav-pills',
      'nav-item',
      'nav-link',
      'active',
      'active-tag',
      'top-header',
      'name',
      'social-link',
      'about-me',
      'about-me__title',
      'about-me__introduction',
      'title',
      'quote',
      'quote__text',
      'quote__author',
      'service',
      'service__description',
      'service__price',
      'form-container',
      'd-block',
      'w-100',
      'carousel',
      'carousel-indicators',
      'carousel-inner',
      'carousel-item',
      'carousel-item-next',
      'carousel-item-start',
      'carousel-control-prev',
      'carousel-control-prev-icon',
      'visually-hidden',
      'carousel-control-next',
      'carousel-control-next-icon',
      'picture',
      'left',
      'container',
      'py-3',
      'fade',
      'right',
      '@media (min-width: 1200px)',
      '@media (min-width: 576px)',
      '@media (min-width: 768px)',
      '@media (min-width: 992px)',
      '@media (min-width: 1400px)',
      '@media (max-width: 575.98px)',
      '@media (max-width: 767.98px)',
      '@media (max-width: 991.98px)',
      '@media (max-width: 1199.98px)',
      '@media (max-width: 1399.98px)',
      '@media (prefers-reduced-motion: reduce)',
      '@media print',
        ],    whitelistPatterns: [/^bg-/, /^text-/], // Ajoutez des motifs de liste blanche si nécessaire
    output: './assets/bootstrap/purged-bootstrap.min.css', // Spécifiez le dossier de sortie pour les fichiers CSS purgés
};